---

port: 4000
host: 0.0.0.0
safe: false


### site serving configuration ###
exclude: [CNAME, README.md, .gitignore]
permalink: / ## disables post output
timezone: null
lsi: false
markdown: kramdown
highlighter: pygments


### content configuration ###
title:       "Code Week 2015 @ UMinho"
keywords:    "CeSIUM, jekyll, Code Week, github, universidade do minho, departamento informatica"
description: "Code Week 2015 no Departamento de Informática da Universidade do Minho, organizada pelo CeSIUM - Centro de Estudantes de Engenharia Informática"
source_link: "https://github.com/cesium/codeweek15"
favicon:     "img/favicon.ico"
touch_icon:  "img/apple-touch-icon.png"
google_analytics_key: UA-49607422-1 ## put YOUR key here to enable tracking! (blank to disable)


### template colors, used site-wide via css ###
colors:
  black:     '#3c3836'
  white:     '#fbf1c7'
  blue:      '#458588'
  green:     '#98971a'
  purple:    '#b16286'
  orange:    '#fab125'
  turquoise: '#0fbfcf'
  red:       '#cc241d'

kramdown:
  auto_ids:  false

sass:
  sass_dir: _includes/_stylesheets
